overrides:
  'sveltekit-superforms>typebox': '1.2.19' # TODO remove once the https://github.com/ciscoheat/sveltekit-superforms/issues/689 issue is resolved
allowBuilds:
  core-js-pure: false
  esbuild: true
